#!/bin/bash
# /etc/init.d/serversys
 
### BEGIN INIT INFO
# Provides: serversys
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: serversys initscript
# Description: This service is used to manage a led
### END INIT INFO
 
case "$1" in
    start)
        echo "Starting serversys"
        sh /home/pi/a_sys.sh &
        ;;
    stop)
        echo "Stopping serversys"
        #killall serversys.py
        kill $(ps aux | grep -m 1 'python3 server_sys.py' | awk '{ print $2 }')
        ;;
    *)
        echo "Usage: service serversys start|stop"
        exit 1
        ;;
esac
exit 0
