# Generated by Django 2.1.3 on 2018-12-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=32)),
                ('humidity', models.CharField(max_length=32)),
                ('shidu', models.CharField(max_length=32)),
                ('guangzhao', models.CharField(max_length=32)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
