# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-27 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=32)),
                ('humidity', models.CharField(max_length=32)),
                ('shidu', models.CharField(max_length=32)),
                ('guangzhao', models.CharField(max_length=32)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
