# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-27 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historyvalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryValue',
        ),
    ]
