# Generated by Django 2.0 on 2019-05-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_historyvalue_shebieid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shebieid',
            field=models.CharField(default=10001, max_length=32),
            preserve_default=False,
        ),
    ]
